apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kubernetes-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-kubernetes-api
  template:
    metadata:
      labels:
        app: hello-kubernetes-api
    spec:
      containers:
      - name: hello-kubernetes-api
        image: hello-kubernetes-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes-api-service
spec:
  selector:
    app: hello-kubernetes-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
